[build]
  functions = "netlify/functions"
  publish = "dist"  # o la carpeta donde tu Astro genera el sitio

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200
  methods = ["POST"]
